### PR TITLE
Changed to jQuery 1.11 for legacy compatibility

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by tagawa** [comment]
Review please somebody (*cough* @tripu)

**Comment by tripu** [comment]
@tagawa, this looks OK, but I can't test easily using w3c/apiary.
Also, I see this projects is not a fork of that one.
Can you fork that one, and submit this as a PR upstream instead, please?

**Comment by tagawa** [comment]
Hmm, just tried again but it won't let me send the PR `w3c/apiary`, even though it's set as upstream.

**Comment by tagawa** [comment]
Going to delete this fork and re-make it.

**Pull request closed without merging**
